apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
  clusterIP: None  # Utilisé pour un service de type headless, si nécessaire pour la réplication
